openapi: 3.0.1
info:
  title: Router Limits Webhooks
  license:
    name: All Rights Reserved, Copyright 2019
  version: 1.1.0
  description: These are the webhooks that Router Limits can fire to your organization-configured endpoint.
servers:
  - url: https://yourapi.example.net/webhooks/routerlimits
paths:
  /:
    post:
      parameters:
        - in: header
          name: x-rl-signatures
          schema:
            type: string
            description: one or more signatures separated by a comma
          required: true
      requestBody:
        content:
          application/json:
            schema:
              title: Webhook
              required:
                - attempt
                - attemptTimestamp
                - data
                - eventId
                - eventTimestamp
                - eventType
              type: object
              properties:
                attempt:
                  type: integer
                attemptTimestamp:
                  type: integer
                eventTimestamp:
                  type: integer
                eventId:
                  type: string
                eventType:
                  $ref: '#/components/schemas/WebhookEventType'
                data:
                  oneOf:
                    - $ref: '#/components/schemas/WebhookAccountCreated'
                    - $ref: '#/components/schemas/WebhookAccountDeleted'
                    - $ref: '#/components/schemas/WebhookAccountSubscribed'
                    - $ref: '#/components/schemas/WebhookAccountMovedIn'
                    - $ref: '#/components/schemas/WebhookAccountMovedOut'
        required: true
      responses:
        204:
          description: webhook succeeded
          content: {}
components:
  schemas:
    Plan:
      type: object
      required:
        - id
        - name
      properties:
        name:
          type: string
          example: Premium Ultra Deluxe
        id:
          type: string
          example: coolPlan3
    WebhookEventType:
      type: string
      enum:
        - ACCOUNT_CREATED
        - ACCOUNT_SUBSCRIBED
        - ACCOUNT_CANCELED
        - ACCOUNT_MOVE_IN
        - ACCOUNT_MOVE_OUT
    WebhookAccountCreated:
      type: object
      required:
        - id
        - user
      properties:
        id:
          type: string
          description: id of the account
        user:
          type: object
          description: Information about the user linked to the account
          required:
            - firstName
            - lastName
            - email
          properties:
            firstName:
              type: string
            lastName:
              type: string
            email:
              type: string
              format: email
    WebhookAccountDeleted:
      type: object
      required:
        - accountId
      properties:
        accountId:
          type: string
          description: id of the account being canceled
          minLength: 1
    WebhookAccountMovedIn:
      $ref: '#/components/schemas/WebhookAccountCreated'
    WebhookAccountMovedOut:
      $ref: '#/components/schemas/WebhookAccountDeleted'
    WebhookAccountSubscribed:
      type: object
      required:
        - accountId
        - plan
      properties:
        accountId:
          type: string
          description: id of the account being subscribed
          minLength: 1
        plan:
          $ref: '#/components/schemas/Plan'

